name: dockerinit

on: 
 workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: nginx-container
        run: docker run -id --name python-con -p 80:80 nginx
      - name: con process
        run: docker ps -a
