---
name: Hello

on: 
  push:
    branches:
      - main
  workflow_dispatch:
     
jobs:
    greet:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout from actions
          uses: actions/checkout@v6

        - name: greet
          run: echo "Hello $USER"
        
        - name: system info
          run: |
            sudo apt update && sudo apt install inxi
            inxi -f
      
        - name: git files
          run: |
            cd /home/runner/work/Github-Action/Github-Action/
            git status
            git log
            git remote -v

            
           

       

