---
name: Hello

on: 
  push:
    branches:
      - main
  workflow_dispatch:
     
jobs:
    greet:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout from actions
          run: actions/checkout@v6

        - name: greet
          run: echo "Hello $USER"

    systeminfo:
      runs-on: ubuntu-latest
      steps:
        - name: system info
          run: uname -a
          
