---
name: Hello

on: 
  workflow_dispatch:
  schedule:
    - cron: '5 * * * *'   

     
jobs:
    greet:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout from actions
          uses: actions/checkout@v6

        - name: greet
          run: echo "Hello $USER"
        
        - name: data and time
          run: date
        
        - name: Branch trigger run
          run: |
            echo "branch= $GITHUB_REF"
            echo "OS= $RUNNER_OS"
            ls
      
        - name: system info
          run: |
            uname -a
            lscpu
            lsmem
      
        - name: git files
          run: |
            pwd
            cd /home/runner/work/Github-Action/Github-Action/
            git status
            git log
            git remote -v
            ls


           

       

