name: WF_manual_input

on:
  workflow_dispatch:
    inputs:
      first_input: 
        description: 'Text to print'
        required: true
        type: string




jobs:
  JB_input:
    runs-on: ubuntu-latest

    steps:
      - name: print input
        run: echo "Your input:${{inputs}}"
