name: WF_multi-os

on:
  workflow_dispatch:
    inputs:
      first_input:
        description: "Type Do it Daddy"
        required: true
        type: string

jobs:
  JB_Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Print System ServerDetails
        run: |
            uname -a
            hostname
            echo "UR: $USER"
      - name: services and version
        run: |
            python --version
            docker --version
            node --version
            git --version

  JB_Windows:
    runs-on: windows-latest
    steps:
      - name: Print System ServerDetails
        run: |
            systeminfo
            hostname
            echo "UR: $USER"
      - name: services and version
        run: |
            python --version
            docker --version
            node --version
            git --version
  
  JB_MacOs:
    runs-on: macos-latest
    steps:
      - name: Print System ServerDetails
        run: |
            uname -a
            hostname
            echo "UR: $USER"
      - name: services and version
        run: |
            python --version
            
            if command -v docker &> /dev/null; then
              docker --version
            else
              echo "Docker not found, skipping..."
            fi
            node --version
            git --version


    