name: WF_Pull_Request_Trigger

on:
  pull_request:
    branches:
      - main

jobs:
  JB_Pull_Request_Trigger:
    runs_on: ubuntu-latest

    steps:
      - name: Check pull request
        run: echo "PR check running for branch:${GITHUB_REF}"
