name: WF_selfhosted

on:
  workflow_dispatch:

jobs:
    JB_selfhosted:
        runs-on: self-hosted
        steps:
          - name: check system
            run: |
                uname -a
                python3 --version
                docker --version
                git --version
                mkdir /home/ubuntu/app && cd /home/ubuntu/app
                touch hello.txt 
                pwd

