name: WF_Tag

on:
  workflow_dispatch:

jobs:
    setup:
        runs-on: [self-hosted,sjrunner-ec2]
        steps:
          - name: check version name
            run: node --version
          - name: user name
            run: echo "runnner= $USER"